# Generated by Django 3.2.7 on 2021-09-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('date_of_receipt', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('unit', models.CharField(max_length=16)),
                ('supplier_name', models.CharField(max_length=32)),
            ],
        ),
    ]
